name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Nombre del paquete del juego:"
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    - name: Configurar Java 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: Hacer Gradle ejecutable
      run: chmod +x ./gradlew
    - name: Modificar archivo Gradle
      run: sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
    - name: Modificar game.h
      run: sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
    - name: Construir Release
      run: ./gradlew :module:assembleRelease
    - name: Subir Artifacto
      uses: actions/upload-artifact@v3
      with:
        name: zygisk-il2cppdumper
        path: out/magisk_module_release/
